/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import crud.crud;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
    crud mycode;

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
        mycode= new crud();
        mycode.tampilDataMasuk(tabelMasuk, "SELECT*FROM masuk");
        mycode.tampilDataStock(tabelStock, "SELECT*FROM stock");
        mycode.tampilDataPeminjaman(tabelPinjam, "SELECT*FROM peminjaman");
        mycode.tampilDataKeluar(tabelKeluar, "SELECT*FROM keluar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlStok = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtJenisBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtDeskripsi = new javax.swing.JTextField();
        btnHpsStock = new javax.swing.JButton();
        btnSmpnStock = new javax.swing.JButton();
        btnUbhStock = new javax.swing.JButton();
        txtCariStock = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelStock = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtSatuan = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        pnlMasuk = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtTanggalMasuk = new javax.swing.JTextField();
        txtIdBarangMasuk = new javax.swing.JTextField();
        txtNotaMasuk = new javax.swing.JTextField();
        btnHpsMasuk = new javax.swing.JButton();
        btnSmpnMasuk = new javax.swing.JButton();
        btnUbhMasuk = new javax.swing.JButton();
        txtCariMasuk = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelMasuk = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        txtIdMasuk = new javax.swing.JTextField();
        txtKeteranganMasuk = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtQtyMasuk = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        pnlKeluar = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtTanggalKeluar = new javax.swing.JTextField();
        txtIdBarangKeluar = new javax.swing.JTextField();
        txtPenerimaKeluar = new javax.swing.JTextField();
        btnHpsKeluar = new javax.swing.JButton();
        btnSmpnKeluar = new javax.swing.JButton();
        btnUbhKeluar = new javax.swing.JButton();
        txtCariKeluar = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelKeluar = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        txtIdKeluar = new javax.swing.JTextField();
        txtKeperluanKeluar = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtQtyKeluar = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        pnlPeminjaman = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtTanggalPinjam = new javax.swing.JTextField();
        txtIdBarangPinjam = new javax.swing.JTextField();
        txtQtyPinjam = new javax.swing.JTextField();
        btnHpsPinjam = new javax.swing.JButton();
        btnSmpnPinjam = new javax.swing.JButton();
        btnUbhPinjam = new javax.swing.JButton();
        txtCariPinjam = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelPinjam = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        txtIdPeminjaman = new javax.swing.JTextField();
        txtStatusPinjam = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtKeperluanPinjam = new javax.swing.JTextField();
        txtPeminjam = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtTanggalKembali = new javax.swing.JTextField();
        txtJumlahKembali = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnStok = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnPeminjaman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        Content.add(pnlHome, "card6");

        pnlStok.setBackground(new java.awt.Color(204, 255, 204));
        pnlStok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Deskripsi");
        pnlStok.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 132, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Jenis Barang");
        pnlStok.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Nama Barang");
        pnlStok.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtJenisBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisBarang.setForeground(new java.awt.Color(0, 0, 0));
        pnlStok.add(txtJenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtNamaBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtNamaBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangActionPerformed(evt);
            }
        });
        pnlStok.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtDeskripsi.setBackground(new java.awt.Color(255, 255, 255));
        txtDeskripsi.setForeground(new java.awt.Color(0, 0, 0));
        pnlStok.add(txtDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsStock.setText("HAPUS");
        btnHpsStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsStockActionPerformed(evt);
            }
        });
        pnlStok.add(btnHpsStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnStock.setText("SIMPAN");
        btnSmpnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnStockActionPerformed(evt);
            }
        });
        pnlStok.add(btnSmpnStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhStock.setText("UBAH");
        btnUbhStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhStockActionPerformed(evt);
            }
        });
        pnlStok.add(btnUbhStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariStock.setBackground(new java.awt.Color(255, 255, 255));
        txtCariStock.setForeground(new java.awt.Color(0, 0, 0));
        txtCariStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariStockKeyReleased(evt);
            }
        });
        pnlStok.add(txtCariStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 370, -1));

        tabelStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelStock);

        pnlStok.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 480, 155));

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("ID Barang");
        pnlStok.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdBarang.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBarang.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBarangActionPerformed(evt);
            }
        });
        pnlStok.add(txtIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Satuan");
        pnlStok.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Stok");
        pnlStok.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtSatuan.setBackground(new java.awt.Color(255, 255, 255));
        txtSatuan.setForeground(new java.awt.Color(0, 0, 0));
        pnlStok.add(txtSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        txtStock.setBackground(new java.awt.Color(255, 255, 255));
        txtStock.setForeground(new java.awt.Color(0, 0, 0));
        txtStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActionPerformed(evt);
            }
        });
        pnlStok.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        Content.add(pnlStok, "card4");

        pnlMasuk.setBackground(new java.awt.Color(204, 255, 204));
        pnlMasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Nota");
        pnlMasuk.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Tanggal");
        pnlMasuk.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("ID Barang Masuk");
        pnlMasuk.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtTanggalMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalMasuk.setForeground(new java.awt.Color(0, 0, 0));
        pnlMasuk.add(txtTanggalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtIdBarangMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBarangMasuk.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBarangMasukActionPerformed(evt);
            }
        });
        pnlMasuk.add(txtIdBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtNotaMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txtNotaMasuk.setForeground(new java.awt.Color(0, 0, 0));
        pnlMasuk.add(txtNotaMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsMasuk.setText("HAPUS");
        btnHpsMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsMasukActionPerformed(evt);
            }
        });
        pnlMasuk.add(btnHpsMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnMasuk.setText("SIMPAN");
        btnSmpnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnMasukActionPerformed(evt);
            }
        });
        pnlMasuk.add(btnSmpnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhMasuk.setText("UBAH");
        btnUbhMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhMasukActionPerformed(evt);
            }
        });
        pnlMasuk.add(btnUbhMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txtCariMasuk.setForeground(new java.awt.Color(0, 0, 0));
        txtCariMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariMasukKeyReleased(evt);
            }
        });
        pnlMasuk.add(txtCariMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 370, -1));

        tabelMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabelMasuk);

        pnlMasuk.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 480, 155));

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("ID Masuk");
        pnlMasuk.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txtIdMasuk.setForeground(new java.awt.Color(0, 0, 0));
        txtIdMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMasukActionPerformed(evt);
            }
        });
        pnlMasuk.add(txtIdMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtKeteranganMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txtKeteranganMasuk.setForeground(new java.awt.Color(0, 0, 0));
        pnlMasuk.add(txtKeteranganMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Keterangan");
        pnlMasuk.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        txtQtyMasuk.setBackground(new java.awt.Color(255, 255, 255));
        txtQtyMasuk.setForeground(new java.awt.Color(0, 0, 0));
        pnlMasuk.add(txtQtyMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Quantity");
        pnlMasuk.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        Content.add(pnlMasuk, "card3");

        pnlKeluar.setBackground(new java.awt.Color(204, 255, 204));
        pnlKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Penerima");
        pnlKeluar.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Tanggal");
        pnlKeluar.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("ID Barang Keluar");
        pnlKeluar.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtTanggalKeluar.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalKeluar.setForeground(new java.awt.Color(0, 0, 0));
        pnlKeluar.add(txtTanggalKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtIdBarangKeluar.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBarangKeluar.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBarangKeluarActionPerformed(evt);
            }
        });
        pnlKeluar.add(txtIdBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtPenerimaKeluar.setBackground(new java.awt.Color(255, 255, 255));
        txtPenerimaKeluar.setForeground(new java.awt.Color(0, 0, 0));
        pnlKeluar.add(txtPenerimaKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsKeluar.setText("HAPUS");
        btnHpsKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsKeluarActionPerformed(evt);
            }
        });
        pnlKeluar.add(btnHpsKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, -1));

        btnSmpnKeluar.setText("SIMPAN");
        btnSmpnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnKeluarActionPerformed(evt);
            }
        });
        pnlKeluar.add(btnSmpnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnUbhKeluar.setText("UBAH");
        btnUbhKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhKeluarActionPerformed(evt);
            }
        });
        pnlKeluar.add(btnUbhKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 80, -1));

        txtCariKeluar.setBackground(new java.awt.Color(255, 255, 255));
        txtCariKeluar.setForeground(new java.awt.Color(0, 0, 0));
        txtCariKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeluarKeyReleased(evt);
            }
        });
        pnlKeluar.add(txtCariKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 370, -1));

        tabelKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tabelKeluar);

        pnlKeluar.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 480, 155));

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("ID Keluar");
        pnlKeluar.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdKeluar.setBackground(new java.awt.Color(255, 255, 255));
        txtIdKeluar.setForeground(new java.awt.Color(0, 0, 0));
        txtIdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdKeluarActionPerformed(evt);
            }
        });
        pnlKeluar.add(txtIdKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtKeperluanKeluar.setBackground(new java.awt.Color(255, 255, 255));
        txtKeperluanKeluar.setForeground(new java.awt.Color(0, 0, 0));
        pnlKeluar.add(txtKeperluanKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Keperluan");
        pnlKeluar.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, -1));

        txtQtyKeluar.setBackground(new java.awt.Color(255, 255, 255));
        txtQtyKeluar.setForeground(new java.awt.Color(0, 0, 0));
        pnlKeluar.add(txtQtyKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 220, -1));

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Quantity");
        pnlKeluar.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 110, -1));

        Content.add(pnlKeluar, "card5");

        pnlPeminjaman.setBackground(new java.awt.Color(204, 255, 204));
        pnlPeminjaman.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Quantity");
        pnlPeminjaman.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        jLabel35.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Tanggal");
        pnlPeminjaman.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jLabel36.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("ID Barang");
        pnlPeminjaman.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        txtTanggalPinjam.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalPinjam.setForeground(new java.awt.Color(0, 0, 0));
        pnlPeminjaman.add(txtTanggalPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 220, -1));

        txtIdBarangPinjam.setBackground(new java.awt.Color(255, 255, 255));
        txtIdBarangPinjam.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBarangPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBarangPinjamActionPerformed(evt);
            }
        });
        pnlPeminjaman.add(txtIdBarangPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 220, -1));

        txtQtyPinjam.setBackground(new java.awt.Color(255, 255, 255));
        txtQtyPinjam.setForeground(new java.awt.Color(0, 0, 0));
        pnlPeminjaman.add(txtQtyPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, -1));

        btnHpsPinjam.setText("HAPUS");
        btnHpsPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpsPinjamActionPerformed(evt);
            }
        });
        pnlPeminjaman.add(btnHpsPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 80, -1));

        btnSmpnPinjam.setText("SIMPAN");
        btnSmpnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmpnPinjamActionPerformed(evt);
            }
        });
        pnlPeminjaman.add(btnSmpnPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        btnUbhPinjam.setText("UBAH");
        btnUbhPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbhPinjamActionPerformed(evt);
            }
        });
        pnlPeminjaman.add(btnUbhPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 80, -1));

        txtCariPinjam.setBackground(new java.awt.Color(255, 255, 255));
        txtCariPinjam.setForeground(new java.awt.Color(0, 0, 0));
        txtCariPinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPinjamKeyReleased(evt);
            }
        });
        pnlPeminjaman.add(txtCariPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 370, -1));

        tabelPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tabelPinjam);

        pnlPeminjaman.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 770, 155));

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("ID Peminjaman");
        pnlPeminjaman.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtIdPeminjaman.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPeminjaman.setForeground(new java.awt.Color(0, 0, 0));
        txtIdPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPeminjamanActionPerformed(evt);
            }
        });
        pnlPeminjaman.add(txtIdPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, -1));

        txtStatusPinjam.setBackground(new java.awt.Color(255, 255, 255));
        txtStatusPinjam.setForeground(new java.awt.Color(0, 0, 0));
        pnlPeminjaman.add(txtStatusPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 220, -1));

        jLabel38.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Status ");
        pnlPeminjaman.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 110, -1));

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Keperluan ");
        pnlPeminjaman.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 110, -1));

        txtKeperluanPinjam.setBackground(new java.awt.Color(255, 255, 255));
        txtKeperluanPinjam.setForeground(new java.awt.Color(0, 0, 0));
        pnlPeminjaman.add(txtKeperluanPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 220, -1));

        txtPeminjam.setBackground(new java.awt.Color(255, 255, 255));
        txtPeminjam.setForeground(new java.awt.Color(0, 0, 0));
        txtPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeminjamActionPerformed(evt);
            }
        });
        pnlPeminjaman.add(txtPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 220, -1));

        jLabel40.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Peminjam");
        pnlPeminjaman.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jLabel50.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Tanggal Kembali");
        pnlPeminjaman.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 140, -1));

        txtTanggalKembali.setBackground(new java.awt.Color(255, 255, 255));
        txtTanggalKembali.setForeground(new java.awt.Color(0, 0, 0));
        pnlPeminjaman.add(txtTanggalKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 220, -1));

        txtJumlahKembali.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlahKembali.setForeground(new java.awt.Color(0, 0, 0));
        txtJumlahKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahKembaliActionPerformed(evt);
            }
        });
        pnlPeminjaman.add(txtJumlahKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 220, -1));

        jLabel51.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Jumlah Kembali");
        pnlPeminjaman.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        Content.add(pnlPeminjaman, "card5");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("APLIKASI MANAJEMEN STOK GUDANG");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(0, 204, 102));
        Menu.setForeground(new java.awt.Color(255, 255, 255));

        btnStok.setBackground(new java.awt.Color(153, 255, 153));
        btnStok.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnStok.setForeground(new java.awt.Color(0, 0, 0));
        btnStok.setText("STOK");
        btnStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStokActionPerformed(evt);
            }
        });

        btnMasuk.setBackground(new java.awt.Color(153, 255, 153));
        btnMasuk.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnMasuk.setForeground(new java.awt.Color(0, 0, 0));
        btnMasuk.setText("BARANG MASUK");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(153, 255, 153));
        btnKeluar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(0, 0, 0));
        btnKeluar.setText("BARANG KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(153, 255, 153));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPeminjaman.setBackground(new java.awt.Color(153, 255, 153));
        btnPeminjaman.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPeminjaman.setForeground(new java.awt.Color(0, 0, 0));
        btnPeminjaman.setText("PEMINJAMAN");
        btnPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeminjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMasuk)
                    .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPeminjaman, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnKeluar, btnMasuk, btnPeminjaman, btnStok});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStok, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMasuk)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar)
                .addGap(18, 18, 18)
                .addComponent(btnPeminjaman)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnKeluar, btnMasuk, btnPeminjaman, btnStok});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStokActionPerformed
        Content.removeAll(); 
        Content.add(pnlStok);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnStokActionPerformed

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        Content.removeAll(); 
        Content.add(pnlMasuk);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        Content.removeAll(); 
        Content.add(pnlKeluar);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeminjamanActionPerformed
        Content.removeAll(); 
        Content.add(pnlPeminjaman);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnPeminjamanActionPerformed

    private void txtCariStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariStockKeyReleased
        String c = txtCariStock.getText();
        String cari = "SELECT*FROM stock WHERE idbarang LIKE '%"+c+"%'"+
                      "OR namabarang LIKE '%"+c+"%' OR jenisbarang LIKE '%"+c+"%'"+
                      "OR deskripsi LIKE '%"+c+"%' OR satuan LIKE '%"+c+"%'";
        mycode.tampilDataStock(tabelStock, cari);
    }//GEN-LAST:event_txtCariStockKeyReleased

    private void btnUbhStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhStockActionPerformed
        try {
               mycode.ubahStock(txtIdBarang.getText(), txtNamaBarang.getText(),
                                txtJenisBarang.getText(), txtDeskripsi.getText(),
                                txtStock.getText(), txtSatuan.getText());

               // Refresh tabel
               mycode.tampilDataStock(tabelStock, "SELECT*FROM stock");
           } catch (Exception e) {
           }
    }//GEN-LAST:event_btnUbhStockActionPerformed

    private void btnSmpnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnStockActionPerformed
        try {
            if(txtIdBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Barang Belum Diisi");
                txtIdBarang.requestFocus();
            } else if(txtNamaBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nama Barang Belum Diisi");
                txtNamaBarang.requestFocus();
            } else if(txtJenisBarang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Jenis Barang Belum Diisi");
                txtJenisBarang.requestFocus();
            } else if(txtDeskripsi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Deskripsi Belum Diisi");
                txtDeskripsi.requestFocus();
            } else if(txtStock.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Stock Belum Diisi");
                txtStock.requestFocus();
            } else if(txtSatuan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Satuan Belum Diisi");
                txtSatuan.requestFocus();
            } else {
                // Sesuai pola, memanggil simpan02 untuk keamanan dan cek duplikasi
                mycode.simpanStock02(txtIdBarang.getText(), txtNamaBarang.getText(),
                                     txtJenisBarang.getText(), txtDeskripsi.getText(),
                                     txtStock.getText(), txtSatuan.getText());

                mycode.tampilDataStock(tabelStock, "SELECT*FROM stock");
                if (mycode.duplikasi == true){
                    txtNamaBarang.setText(mycode.CEK_NAMABARANG);
                    txtJenisBarang.setText(mycode.CEK_JENISBARANG);
                    txtDeskripsi.setText(mycode.CEK_DESKRIPSI);
                    txtStock.setText(mycode.CEK_STOCK);
                    txtSatuan.setText(mycode.CEK_SATUAN);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnStockActionPerformed

    private void btnHpsStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsStockActionPerformed
        try {
            mycode.hapusStock(txtIdBarang.getText());
            mycode.tampilDataStock(tabelStock, "SELECT*FROM stock");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsStockActionPerformed

    private void txtNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangActionPerformed

    private void txtIdBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBarangActionPerformed

    private void txtIdBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBarangMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBarangMasukActionPerformed

    private void btnHpsMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsMasukActionPerformed
        try {
            mycode.hapusMasuk(txtIdMasuk.getText());
            mycode.tampilDataMasuk(tabelMasuk, "SELECT*FROM masuk");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsMasukActionPerformed

    private void btnSmpnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnMasukActionPerformed
        try {
            if(txtIdMasuk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Masuk Belum Diisi");
                txtIdMasuk.requestFocus();
            } else if(txtIdBarangMasuk.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "ID Barang Belum Diisi");
                txtIdBarangMasuk.requestFocus();
            } else if(txtTanggalMasuk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Belum Diisi");
                txtTanggalMasuk.requestFocus();
            } else if(txtNotaMasuk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Nota Belum Diisi");
                txtNotaMasuk.requestFocus();
            } else if(txtKeteranganMasuk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Keterangan Belum Diisi");
                txtKeteranganMasuk.requestFocus();
            } else if(txtQtyMasuk.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Qty Belum Diisi");
                txtQtyMasuk.requestFocus();
            } else {
                mycode.simpanMasuk02(txtIdMasuk.getText(), txtIdBarangMasuk.getText(),
                                     txtTanggalMasuk.getText(), txtNotaMasuk.getText(),
                                     txtKeteranganMasuk.getText(), txtQtyMasuk.getText());

                mycode.tampilDataMasuk(tabelMasuk, "SELECT*FROM masuk");

                if (mycode.duplikasi == true){
                    txtIdBarangMasuk.setText(mycode.CEK_IDBARANG_MASUK);
                    txtTanggalMasuk.setText(mycode.CEK_TANGGAL_MASUK);
                    txtNotaMasuk.setText(mycode.CEK_NOTA_MASUK);
                    txtKeteranganMasuk.setText(mycode.CEK_KETERANGAN_MASUK);
                    txtQtyMasuk.setText(mycode.CEK_QTY_MASUK);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnMasukActionPerformed

    private void btnUbhMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhMasukActionPerformed
        try {
            mycode.ubahMasuk(txtIdMasuk.getText(), txtIdBarangMasuk.getText(),
                             txtTanggalMasuk.getText(), txtNotaMasuk.getText(),
                             txtKeteranganMasuk.getText(), txtQtyMasuk.getText());

            mycode.tampilDataMasuk(tabelMasuk, "SELECT*FROM masuk");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhMasukActionPerformed

    private void txtCariMasukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariMasukKeyReleased
        String c = txtCariMasuk.getText();
        String cari = "SELECT*FROM masuk WHERE idmasuk LIKE '%"+c+"%'"+
                      "OR idbarang LIKE '%"+c+"%' OR tanggal LIKE '%"+c+"%'"+
                      "OR nota LIKE '%"+c+"%' OR keterangan LIKE '%"+c+"%'";
        mycode.tampilDataMasuk(tabelMasuk, cari);
    }//GEN-LAST:event_txtCariMasukKeyReleased

    private void txtIdMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMasukActionPerformed

    private void txtIdBarangPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBarangPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBarangPinjamActionPerformed

    private void btnHpsPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsPinjamActionPerformed
        try {
            mycode.hapusPeminjaman(txtIdPeminjaman.getText());
            mycode.tampilDataPeminjaman(tabelPinjam, "SELECT*FROM peminjaman");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsPinjamActionPerformed

    private void btnSmpnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnPinjamActionPerformed
        try {
            if(txtIdPeminjaman.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Peminjaman Belum Diisi");
                txtIdPeminjaman.requestFocus();
            } else if(txtIdBarangPinjam.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "ID Barang Belum Diisi");
                txtIdBarangPinjam.requestFocus();
            } else if(txtTanggalPinjam.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Pinjam Belum Diisi");
                txtTanggalPinjam.requestFocus();
            } else if(txtQtyPinjam.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Qty Belum Diisi");
                txtQtyPinjam.requestFocus();
            } else if(txtPeminjam.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Peminjam Belum Diisi");
                txtPeminjam.requestFocus();
            } else if(txtKeperluanPinjam.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Keperluan Belum Diisi");
                txtKeperluanPinjam.requestFocus();
            } else if(txtStatusPinjam.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Status Belum Diisi");
                txtStatusPinjam.requestFocus();
            } else if(txtJumlahKembali.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Jumlah Kembali Belum Diisi");
                txtJumlahKembali.requestFocus();
            } else if(txtTanggalKembali.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Kembali Belum Diisi");
                txtTanggalKembali.requestFocus();
            } else {
                mycode.simpanPeminjaman02(txtIdPeminjaman.getText(), txtIdBarangPinjam.getText(),
                                         txtTanggalPinjam.getText(), txtQtyPinjam.getText(),
                                         txtPeminjam.getText(), txtKeperluanPinjam.getText(),
                                         txtStatusPinjam.getText(), txtJumlahKembali.getText(),
                                         txtTanggalKembali.getText());

                mycode.tampilDataPeminjaman(tabelPinjam, "SELECT*FROM peminjaman");

                if (mycode.duplikasi == true){
                    txtIdBarangPinjam.setText(mycode.CEK_IDBARANG_PINJAM);
                    txtTanggalPinjam.setText(mycode.CEK_TANGGALPINJAM);
                    txtQtyPinjam.setText(mycode.CEK_QTY_PINJAM);
                    txtPeminjam.setText(mycode.CEK_PEMINJAM);
                    txtKeperluanPinjam.setText(mycode.CEK_KEPERLUAN_PINJAM);
                    txtStatusPinjam.setText(mycode.CEK_STATUS_PINJAM);
                    txtJumlahKembali.setText(mycode.CEK_JUMLAHKEMBALI);
                    txtTanggalKembali.setText(mycode.CEK_TANGGALKEMBALI);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnPinjamActionPerformed

    private void btnUbhPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhPinjamActionPerformed
        try {
            mycode.ubahPeminjaman(txtIdPeminjaman.getText(), txtIdBarangPinjam.getText(),
                                 txtTanggalPinjam.getText(), txtQtyPinjam.getText(),
                                 txtPeminjam.getText(), txtKeperluanPinjam.getText(),
                                 txtStatusPinjam.getText(), txtJumlahKembali.getText(),
                                 txtTanggalKembali.getText());

            mycode.tampilDataPeminjaman(tabelPinjam, "SELECT*FROM peminjaman");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhPinjamActionPerformed

    private void txtCariPinjamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPinjamKeyReleased
        String c = txtCariPinjam.getText();
        String cari = "SELECT*FROM peminjaman WHERE idpeminjaman LIKE '%"+c+"%'"+
                      "OR idbarang LIKE '%"+c+"%' OR tanggalpinjam LIKE '%"+c+"%'"+
                      "OR peminjam LIKE '%"+c+"%' OR status LIKE '%"+c+"%'";
        mycode.tampilDataPeminjaman(tabelPinjam, cari);
    }//GEN-LAST:event_txtCariPinjamKeyReleased

    private void txtIdPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPeminjamanActionPerformed

    private void txtPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeminjamActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void txtIdBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBarangKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBarangKeluarActionPerformed

    private void btnHpsKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpsKeluarActionPerformed
        try {
            mycode.hapusKeluar(txtIdKeluar.getText());
            mycode.tampilDataKeluar(tabelKeluar, "SELECT*FROM keluar");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHpsKeluarActionPerformed

    private void btnSmpnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmpnKeluarActionPerformed
        try {
            if(txtIdKeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "ID Keluar Belum Diisi");
                txtIdKeluar.requestFocus();
            } else if(txtIdBarangKeluar.getText().isEmpty()){ // Asumsi nama field beda
                JOptionPane.showMessageDialog(null, "ID Barang Belum Diisi");
                txtIdBarangKeluar.requestFocus();
            } else if(txtTanggalKeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Tanggal Belum Diisi");
                txtTanggalKeluar.requestFocus();
            } else if(txtPenerimaKeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Penerima Belum Diisi");
                txtPenerimaKeluar.requestFocus();
            } else if(txtKeperluanKeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Keperluan Belum Diisi");
                txtKeperluanKeluar.requestFocus();
            } else if(txtQtyKeluar.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Qty Belum Diisi");
                txtQtyKeluar.requestFocus();
            } else {
                mycode.simpanKeluar02(txtIdKeluar.getText(), txtIdBarangKeluar.getText(),
                                      txtTanggalKeluar.getText(), txtPenerimaKeluar.getText(),
                                      txtKeperluanKeluar.getText(), txtQtyKeluar.getText());
                
                mycode.tampilDataKeluar(tabelKeluar, "SELECT*FROM keluar");

                if (mycode.duplikasi == true){
                    txtIdBarangKeluar.setText(mycode.CEK_IDBARANG_KELUAR);
                    txtTanggalKeluar.setText(mycode.CEK_TANGGAL_KELUAR);
                    txtPenerimaKeluar.setText(mycode.CEK_PENERIMA_KELUAR);
                    txtKeperluanKeluar.setText(mycode.CEK_KEPERLUAN_KELUAR);
                    txtQtyKeluar.setText(mycode.CEK_QTY_KELUAR);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSmpnKeluarActionPerformed

    private void btnUbhKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbhKeluarActionPerformed
        try {
            mycode.ubahKeluar(txtIdKeluar.getText(), txtIdBarangKeluar.getText(),
                              txtTanggalKeluar.getText(), txtPenerimaKeluar.getText(),
                              txtKeperluanKeluar.getText(), txtQtyKeluar.getText());

            mycode.tampilDataKeluar(tabelKeluar, "SELECT*FROM keluar");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbhKeluarActionPerformed

    private void txtCariKeluarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeluarKeyReleased
        String c = txtCariKeluar.getText();
        String cari = "SELECT*FROM keluar WHERE idkeluar LIKE '%"+c+"%'"+
                      "OR idbarang LIKE '%"+c+"%' OR tanggal LIKE '%"+c+"%'"+
                      "OR penerima LIKE '%"+c+"%' OR keperluan LIKE '%"+c+"%'";
        mycode.tampilDataKeluar(tabelKeluar, cari);
    }//GEN-LAST:event_txtCariKeluarKeyReleased

    private void txtIdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeluarActionPerformed

    private void txtJumlahKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHpsKeluar;
    private javax.swing.JButton btnHpsMasuk;
    private javax.swing.JButton btnHpsPinjam;
    private javax.swing.JButton btnHpsStock;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnSmpnKeluar;
    private javax.swing.JButton btnSmpnMasuk;
    private javax.swing.JButton btnSmpnPinjam;
    private javax.swing.JButton btnSmpnStock;
    private javax.swing.JButton btnStok;
    private javax.swing.JButton btnUbhKeluar;
    private javax.swing.JButton btnUbhMasuk;
    private javax.swing.JButton btnUbhPinjam;
    private javax.swing.JButton btnUbhStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKeluar;
    private javax.swing.JPanel pnlMasuk;
    private javax.swing.JPanel pnlPeminjaman;
    private javax.swing.JPanel pnlStok;
    private javax.swing.JTable tabelKeluar;
    private javax.swing.JTable tabelMasuk;
    private javax.swing.JTable tabelPinjam;
    private javax.swing.JTable tabelStock;
    private javax.swing.JTextField txtCariKeluar;
    private javax.swing.JTextField txtCariMasuk;
    private javax.swing.JTextField txtCariPinjam;
    private javax.swing.JTextField txtCariStock;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtIdBarangKeluar;
    private javax.swing.JTextField txtIdBarangMasuk;
    private javax.swing.JTextField txtIdBarangPinjam;
    private javax.swing.JTextField txtIdKeluar;
    private javax.swing.JTextField txtIdMasuk;
    private javax.swing.JTextField txtIdPeminjaman;
    private javax.swing.JTextField txtJenisBarang;
    private javax.swing.JTextField txtJumlahKembali;
    private javax.swing.JTextField txtKeperluanKeluar;
    private javax.swing.JTextField txtKeperluanPinjam;
    private javax.swing.JTextField txtKeteranganMasuk;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNotaMasuk;
    private javax.swing.JTextField txtPeminjam;
    private javax.swing.JTextField txtPenerimaKeluar;
    private javax.swing.JTextField txtQtyKeluar;
    private javax.swing.JTextField txtQtyMasuk;
    private javax.swing.JTextField txtQtyPinjam;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtStatusPinjam;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTanggalKeluar;
    private javax.swing.JTextField txtTanggalKembali;
    private javax.swing.JTextField txtTanggalMasuk;
    private javax.swing.JTextField txtTanggalPinjam;
    // End of variables declaration//GEN-END:variables
}
